# Generated by Django 3.2.4 on 2021-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=65)),
                ('mensagem', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira', models.CharField(max_length=20)),
                ('segunda', models.CharField(max_length=20)),
                ('terceira', models.CharField(max_length=20)),
                ('quarta', models.CharField(max_length=20)),
                ('quinta', models.CharField(max_length=20)),
                ('sexta', models.CharField(max_length=20)),
                ('setima', models.CharField(max_length=20)),
                ('oitava', models.CharField(max_length=20)),
                ('nona', models.CharField(max_length=20)),
                ('decima', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('email', models.FileField(upload_to='email/%Y/%m/%d/')),
            ],
        ),
    ]
