# Generated by Django 3.2.3 on 2021-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210531_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=65),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.FileField(upload_to='email/%Y/%m/%d/'),
        ),
    ]
