# Generated by Django 3.2.3 on 2021-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210603_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensagem',
            field=models.TextField(max_length=2000),
        ),
    ]
